# Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#    `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "shittdock-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "shittdock-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "shittdock" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
